[package]
name = "retry"
version = "0.1.0"
edition = "2021"

[features]
default = ["rand"]

[dependencies]
rand = { version = "0.8", optional = true }
tracing = "0.1"
wasm-timer = "0.2.5"

[dev-dependencies]
approx = "0.5.1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
